AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  MaintenanceBroker

  Sample SAM Template for MaintenanceBroker

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  MaintenanceBrokerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: broker/
      Handler: app.lambda_handler
      Runtime: python3.8
      MemorySize: 256
      FunctionName:  MaintenanceBroker-Dev
      Role: arn:aws:iam::901034071818:role/lambda-vpc-role
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          ENVIRONMENT_TYPE: local
          CAG_private_key: CAG_Private_Key-Dev
          CAG_public_key: CAG_Public_Key-Dev
          CAG_REGION: us-east-1
          CAG_CAMP_FUNCTION: CampProxy-Dev
          CAG_Rusada_FUNCTION: RusadaProxy-Dev

      Events:
        MaintenanceBroker:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /ReadAll
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MaintenanceBrokerApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  MaintenanceBrokerFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt MaintenanceBrokerFunction.Arn


