AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  MaintenanceBroker

  Sample SAM Template for MaintenanceBroker

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  MaintenanceBrokerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: broker/
      Handler: app.lambda_handler
      Runtime: python3.8
      MemorySize: 256
      FunctionName: MaintenanceBroker-Prod
      Role: arn:aws:iam::786433678211:role/lambda-vpc-role
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          ENVIRONMENT_TYPE: PROD
          CAG_private_key: CAG_Private_Key-Prod
          CAG_public_key: CAG_Public_Key-Prod
          CAG_REGION: us-east-1
          CAG_CAMP_FUNCTION: CampProxy-Prod
          CAG_Rusada_FUNCTION: RusadaProxy-Prod

      Events:
        MaintenanceBroker:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /ReadAll
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MaintenanceBrokerFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt MaintenanceBrokerFunction.Arn
